/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dinuka Raneesh Anton Gomez
 * @StudentID 2016087
 * @UoWID 16266986
 * @group A
 * @semester 01
 * @coursework 02
 * @level 04
 * @intake September 2016
 * @references Lines 463-468 referenced from: http://stackoverflow.com/questions/26075081/java-application-restart-or-reset-button
 */
import javax.swing.*;
import java.util.*;

public class Hangman extends JFrame {
    int crctLetter;
    String guessWord;
    int incrctLetter;    
    
    //Defining String array to store predefined words
    String[] word = {"dog","bird","hello","forest","complex","oxygenized"};
    
    //Creating new image objects for hangman (line 31 - 39)
    ImageIcon pic1 = new ImageIcon(getClass().getResource("stage1.png"));
    ImageIcon pic2 = new ImageIcon(getClass().getResource("stage2.png"));
    ImageIcon pic3 = new ImageIcon(getClass().getResource("stage3.png"));
    ImageIcon pic4 = new ImageIcon(getClass().getResource("stage4.png"));
    ImageIcon pic5 = new ImageIcon(getClass().getResource("stage5.png"));
    ImageIcon pic6 = new ImageIcon(getClass().getResource("stage6.png"));
    ImageIcon pic7 = new ImageIcon(getClass().getResource("stage7.png"));
    ImageIcon pic8 = new ImageIcon(getClass().getResource("stage8.png"));
    ImageIcon pic9 = new ImageIcon(getClass().getResource("hangmanlose.gif"));
   
    /**
     * Creates new form Hangman
     */
    public Hangman() {
        super("Guess the Word");
        initComponents();      
        guessWord = Randomize(word);//Calling Randomize method to return a random word
        
        /*Using if statement blocks to display only the amount 
        *of Xs as the length of the word returned above(line 53 - 87)
        */
        
        if (guessWord.equals(word[0])) {
            wrdLbl4.setVisible(false);
            wrdLbl5.setVisible(false);
            wrdLbl6.setVisible(false);
            wrdLbl7.setVisible(false);
            wrdLbl8.setVisible(false);
            wrdLbl9.setVisible(false);
            wrdLbl10.setVisible(false);
            hintLbl.setText("HINT: Man's best friend, indeed!");
        }
        if (guessWord.equals(word[1])) {            
            wrdLbl5.setVisible(false);
            wrdLbl6.setVisible(false);
            wrdLbl7.setVisible(false);
            wrdLbl8.setVisible(false);
            wrdLbl9.setVisible(false);
            wrdLbl10.setVisible(false);
            hintLbl.setText("HINT: Winged creature of the skies");
        }
        if (guessWord.equals(word[2])) {            
            wrdLbl6.setVisible(false);
            wrdLbl7.setVisible(false);
            wrdLbl8.setVisible(false);
            wrdLbl9.setVisible(false);
            wrdLbl10.setVisible(false);
            hintLbl.setText("HINT: A greeting!");
        }
        if (guessWord.equals(word[3])) {
            wrdLbl7.setVisible(false);
            wrdLbl8.setVisible(false);
            wrdLbl9.setVisible(false);
            wrdLbl10.setVisible(false);
            hintLbl.setText("HINT: Where flora and fauna coexist");
        }
        if (guessWord.equals(word[4])) {
            wrdLbl8.setVisible(false);
            wrdLbl9.setVisible(false);
            wrdLbl10.setVisible(false);
            hintLbl.setText("HINT: If it's not simple, it's...");
        }
        if(guessWord.equals(word[5])) {
            hintLbl.setText("HINT: Having been given oxygen");
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attemptsLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hangBtn = new javax.swing.JButton();
        wrdLbl1 = new javax.swing.JLabel();
        wrdLbl2 = new javax.swing.JLabel();
        wrdLbl3 = new javax.swing.JLabel();
        wrdLbl4 = new javax.swing.JLabel();
        wrdLbl5 = new javax.swing.JLabel();
        wrdLbl6 = new javax.swing.JLabel();
        charmsglbl = new javax.swing.JLabel();
        txtWord = new javax.swing.JTextField();
        btnTry = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        attemptMsgLbl = new javax.swing.JLabel();
        wrdLbl7 = new javax.swing.JLabel();
        wrdLbl8 = new javax.swing.JLabel();
        wrdLbl9 = new javax.swing.JLabel();
        wrdLbl10 = new javax.swing.JLabel();
        restartBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        hintLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));

        attemptsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(153, 135, 14));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmantitle.gif"))); // NOI18N

        hangBtn.setBackground(new java.awt.Color(0, 0, 0));
        hangBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stage1.png"))); // NOI18N

        wrdLbl1.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl1.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl1.setText("X");

        wrdLbl2.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl2.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl2.setText("X");

        wrdLbl3.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl3.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl3.setText("X");

        wrdLbl4.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl4.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl4.setText("X");

        wrdLbl5.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl5.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl5.setText("X");

        wrdLbl6.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl6.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl6.setText("X");

        charmsglbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        charmsglbl.setText("Enter your character");

        txtWord.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtWord.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnTry.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTry.setForeground(new java.awt.Color(255, 255, 255));
        btnTry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/try it now.png"))); // NOI18N
        btnTry.setBorder(null);
        btnTry.setBorderPainted(false);
        btnTry.setContentAreaFilled(false);
        btnTry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Incorrect Attempts");

        attemptMsgLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attemptMsgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attemptMsgLbl.setText("0");

        wrdLbl7.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl7.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl7.setText("X");

        wrdLbl8.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl8.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl8.setText("X");

        wrdLbl9.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl9.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl9.setText("X");

        wrdLbl10.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        wrdLbl10.setForeground(new java.awt.Color(255, 255, 0));
        wrdLbl10.setText("X");

        restartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restart.png"))); // NOI18N
        restartBtn.setBorderPainted(false);
        restartBtn.setContentAreaFilled(false);
        restartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restartBtn.setDefaultCapable(false);
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLICK TO RESTART");

        hintLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hintLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(wrdLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wrdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(charmsglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(wrdLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wrdLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wrdLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wrdLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wrdLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wrdLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wrdLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wrdLbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(attemptMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTry)
                                    .addComponent(hintLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(restartBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(11, 11, 11))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wrdLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrdLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrdLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrdLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrdLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrdLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrdLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrdLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrdLbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(charmsglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnTry, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hangBtn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(attemptMsgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addComponent(hintLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(restartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(attemptsLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attemptsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryActionPerformed
        try{
            char[] word = guessWord.toCharArray();
            char letter = txtWord.getText().toLowerCase().charAt(0);
            txtWord.requestFocus();//Gets focus on the textfield component for cursor to keep blinking in textfield
            
            int incrct = 0;
            for (int i = 0;i < word.length;i++) {
                
                if (word[i] == letter) {
                /*Replaces an X with the input character everytime a
                *correct letter is input
                */
                    switch (i) {
                        case 0:
                        wrdLbl1.setText(String.valueOf(letter));
                        break;
                        case 1:
                        wrdLbl2.setText(String.valueOf(letter));
                        break;
                        case 2:
                        wrdLbl3.setText(String.valueOf(letter));
                        break;
                        case 3:
                        wrdLbl4.setText(String.valueOf(letter));
                        break;
                        case 4:
                        wrdLbl5.setText(String.valueOf(letter));
                        break;
                        case 5:
                        wrdLbl6.setText(String.valueOf(letter));
                        break;
                        case 6:
                        wrdLbl7.setText(String.valueOf(letter));
                        break;
                        case 7:
                        wrdLbl8.setText(String.valueOf(letter));
                        break;
                        case 8:
                        wrdLbl9.setText(String.valueOf(letter));
                        break;
                        case 9:
                        wrdLbl10.setText(String.valueOf(letter));
                        break;
                        default:
                        break;
                    }
                    crctLetter++;
                }
                else {
                    incrct++;
                }

                if (incrct == word.length) {
                    incrct = 0;
                    incrctLetter++;
                    attemptMsgLbl.setText(Integer.toString(incrctLetter));
                    //Displays the no. of incorrect attempts in the label
                }

                txtWord.setText(null);//Makes textfield empty everytime the tryBtn is clicked            

                if (crctLetter == word.length) {
                    ImageIcon winimg = new ImageIcon(getClass().getResource("win1.gif"));
                    JOptionPane.showMessageDialog(null, "", "Congratulations! YOU WIN!", 
                            JOptionPane.INFORMATION_MESSAGE, winimg);
                    //Opens a JOptionPane and displays the GAME WON image
                    txtWord.setVisible(false);
                    /*Hides the textfield so that user cannot
                    enter more letters after the game is over*/

                }

                /*Updates the hangman button with a new image everytime an
                *incorrect character is entered
                */
                switch (incrctLetter) {
                    case 1:
                    hangBtn.setIcon(pic2);
                    break;
                    case 2:
                    hangBtn.setIcon(pic3);
                    break;
                    case 3:
                    hangBtn.setIcon(pic4);
                    break;
                    case 4:
                    hangBtn.setIcon(pic5);
                    break;
                    case 5:
                    hangBtn.setIcon(pic8);
                    break;                
                    case 6:
                    hangBtn.setIcon(pic9);
                    ImageIcon loseimg = new ImageIcon(getClass().getResource("lose.gif"));
                    JOptionPane.showMessageDialog(null, "The correct word was " +"\"" + 
                        guessWord + "\"", "GAME OVER!", JOptionPane.INFORMATION_MESSAGE, loseimg);
                    //Opens a JOptionPane and displays the GAME LOST image
                    txtWord.setVisible(false);
                    break;                    
                }
            }
        }
        //Catches the exception that occurs when the try button is clicked without entering a character
        catch(StringIndexOutOfBoundsException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnTryActionPerformed
    
    /*Defining new method for restart button
    *(Lines 463-468 Referenced from: http://stackoverflow.com/questions/26075081/java-application-restart-or-reset-button)
    */
    private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed

            dispose();//Tells Garbage Collector to clean the heap which terminates all processes of the class
            Hangman game = new Hangman();//Recall original settings and layout of class
            game.setVisible(true);
        
    }//GEN-LAST:event_restartBtnActionPerformed
    //Defining a new method for shuffling words
    public static String Randomize(String[] arr) {
        int shuffle = new Random().nextInt(arr.length);
        /*Creates a new object "shuffle" from the Random class and it shuffles the 
        array elements and outputs a random word*/ 
        return arr[shuffle];
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Hangman().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attemptMsgLbl;
    private javax.swing.JLabel attemptsLbl;
    private javax.swing.JButton btnTry;
    private javax.swing.JLabel charmsglbl;
    private javax.swing.JButton hangBtn;
    private javax.swing.JLabel hintLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton restartBtn;
    private javax.swing.JTextField txtWord;
    private javax.swing.JLabel wrdLbl1;
    private javax.swing.JLabel wrdLbl10;
    private javax.swing.JLabel wrdLbl2;
    private javax.swing.JLabel wrdLbl3;
    private javax.swing.JLabel wrdLbl4;
    private javax.swing.JLabel wrdLbl5;
    private javax.swing.JLabel wrdLbl6;
    private javax.swing.JLabel wrdLbl7;
    private javax.swing.JLabel wrdLbl8;
    private javax.swing.JLabel wrdLbl9;
    // End of variables declaration//GEN-END:variables
}
